MVCBog/Models/Image.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCBog.Models
{
    public class Image
    {

        [Key]
        public int Id { get; set; }

        public byte[] BrandImage { get; set; }
    }
}

MVCBog/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCBog.Models;

namespace MVCBog.Controllers
{
    public class ImagesController : Controller
    {
       

        
        //public ActionResult Index()
        //{


        //    //return View();

        //}



        [HttpPost]
        public ActionResult AddImage(Image model, HttpPostedFileBase image1)
        {
            var db = new ApplicationDbContext();
            if (image1 != null)
            {
                model.BrandImage = new byte[image1.ContentLength];
                image1.InputStream.Read(model.BrandImage, 0, image1.ContentLength);
            }
            db.Img.Add(model);
            db.SaveChanges();
            return View(model);

        }


    }
}

MVCBog/Views/Images/AddImage.cshtml
@model MVCBog.Models.Image

@{
    ViewBag.Title = "AddImage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AddImage</h2>


@using (Html.BeginForm("AddImage", "Images", FormMethod.Post, new {enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Image</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BrandImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               <input type="file" name="image12" id="image12" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}