MVCBog/Controllers/AboutusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Net.Mail;
using System.Text;
using System.Web.Mvc;
using MVCBog.Models;
using System.Net;
using System.Threading.Tasks;

namespace MVCBog.Controllers
{
    public class AboutusController : Controller
    {
        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Contacts()
        {
            return View();
        }


    }
    }

MVCBog/Controllers/AdsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCBog.Extensions;
using MVCBog.Models;

namespace MVCBog.Controllers
{
    public class AdsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Posts
        public ActionResult Index()
        {
            var ads = db.Ads.Include(p => p.Author).ToList();

            //var item = (from d in db.Ads
            //            select d).ToList();
            //return View(db.Ads.Include(p=>p.Author).ToList());
            var posts = db.Ads
             .OrderByDescending(p => p.Date);
            return View(posts.ToList());
        }

        public ActionResult Search(string searchString)
        {

            var ads = from m in db.Ads
                      select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                ads = ads.Where(s => s.Title.Contains(searchString)).OrderByDescending(p => p.Date);
            }

            return View(ads.ToList());
        }

        // GET: Posts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ads ads = db.Ads.Find(id);
            if (ads == null)
            {
                return HttpNotFound();
            }
            return View(ads);
        }

        // GET: Posts/Create
        [Authorize]
        public ActionResult Create()
        {
            Ads b1 = new Ads();
            return View(b1);
        }

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Body,Price,Contacts")] Ads ads,  HttpPostedFileBase image1)
        {


            if (ModelState.IsValid)
            {
                
                ads.Author = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
       
                this.AddNotification("Обявата е публикувана успешно", NotificationType.SUCCESS);
                //return RedirectToAction("Index");
            }

            if (image1 != null)
            {
                ads.UplImage = new byte[image1.ContentLength];
                image1.InputStream.Read(ads.UplImage, 0, image1.ContentLength);


            }
            db.Ads.Add(ads);
            db.SaveChanges();

            return View(ads);

      
           
        }

        // GET: Posts/Edit/5
        [Authorize(Roles = "Administrators")]

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ads ads = db.Ads.Find(id);
            if (ads == null)
            {
                return HttpNotFound();
            }
            //var authors = db.Users.ToList();
            //ViewBag.Authors = authors;
            return View(ads);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrators")]
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Body,Date,Contacts,Price")] Ads ads)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ads).State = EntityState.Modified;
                db.Entry(ads).Property("UplImage").IsModified = false;
                db.SaveChanges();
                this.AddNotification("Обявата е редактирана", NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }
            return View(ads);
        }

        // GET: Posts/Delete/5
        [Authorize(Roles = "Administrators")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ads ads = db.Ads.Find(id);
            if (ads == null)
            {
                return HttpNotFound();
            }
            return View(ads);
        }

        // POST: Posts/Delete/5
        [Authorize(Roles="Administrators")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ads ads = db.Ads.Find(id);
            db.Ads.Remove(ads);
            db.SaveChanges();
            this.AddNotification("Обявата беше изтрита", NotificationType.SUCCESS);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCBog/Controllers/PollController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCBog.Controllers
{
    public class PollController : Controller
    {
        
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVCBog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cars</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cars SoftUni", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Начало", "Index", "Home")</li>*@
                    <li>@Html.ActionLink("Обяви", "Index", "Ads")</li>
                    <li>@Html.ActionLink("Публикувай нова обява", "Create", "Ads")</li>
                    <li>@Html.ActionLink("Търсене", "Search", "Ads")</li>
                    @*<li>@Html.ActionLink("Анкета", "index", "Poll")</li>*@
                    <li>@Html.ActionLink("За нас", "index", "Aboutus")</li>
                    <li>@Html.ActionLink("Контакти", "Contacts", "Aboutus")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
<div class="container body-content">
    @Html.Partial("_Notifications")
    @RenderBody()
    <hr/>
    <div>Брой уникални потребители на сайта</div>
    <!-- hitwebcounter Code START -->
    <a href="http://www.hitwebcounter.com" target="_blank">
        <img src="http://hitwebcounter.com/counter/counter.php?page=6479486&style=0025&nbdigits=5&type=ip&initCount=0" title="" Alt="" border="0">
    </a>                                        <br />
    <!-- hitwebcounter.com --><a href="http://www.hitwebcounter.com" title="Free Visits Counter"
                                 target="_blank" style="font-family: Geneva, Arial, Helvetica;
                                        font-size: 10px; color: #B3B7B3; text-decoration: underline ;">
   
    </a>   
    
    <footer>
        <p>&copy; @DateTime.Now.Year - Cars SoftUni</p>
    </footer>
</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>